### ISSUE TITLE
Description sur virement

### ISSUE THREAD

**Issue by mattgu74** [payutc/casper#1]
On m'a soumis l'idée d'ajouter une description au virement.
Genre pour expliquer ce que concerne le virement, ou juste pour dire merci...

Exemple : "Remboursement kebab 19/09" ou "Merci pour mon repas d'hier midi" ...

Je trouve l'idée cool, à réfléchir.

**Comment by apuyou** [comment]
Done in 10b9c27275bc271041e29d2e4eb2d4302d6765b8
