### ISSUE TITLE
Pouvoir choisir de vouloir ou pas un ticket papier au paiement

### ISSUE THREAD

**Issue by Elektordi** [payutc/casper#13]
_Les tickets papier c'est bien, mais sauver la planète, les ours polaires, toussa toussa, c'est mieux !_

Il faudrait une option sur casper pour qu'un utilisateur puisse choisir si il veut un ticket papier ou pas à chaque achat. Voir même une liste: ticket papier (si dispo), ticket par email, jamais de ticket.

**Comment by mattgu74** [comment]
Plusieurs features dans ta requête:
- Le ticket mail, il est sur les rails y'a une issue sur le serveur qui parle des mails justement.
- Le fait de pouvoir choisir de recevoir ou non ce ticket, bien vu ce n'était pas prévu pour le moment.
- Le fait de choisir de ne pas vouloir de ticket papier.

Pour le troisième point, j'ai un doute sur le fait qu'on le veuille, sur le papier c'est cool et bien, et si je n'étais que membre de payutc je sauterais dessus. Mais ayant été membre du pic deux semestre consécutifs, je sais que la sortie du ticket est synonyme de succès de la vente pour les permanenciers. Le taux de perte augmente quand il n'y a pas de ticket (tu ne fais pas attention au message qui dit "pas assez de crédit" et tu vends le produit alors que la personne n'a pas été débité...) 

Bref, il faudrait voir avec le pic, si ils en veulent vraiment de cette feature.
