### ISSUE TITLE
Ajouter un moyen de contact

### ISSUE THREAD

**Issue by apuyou** [payutc/casper#2]
Permettre aux gens de contacter payutc (payutc@assos.utc.fr) depuis casper.

**Comment by trecouvr** [comment]
Le mail écrit qurlquepart ca suffit ?

**Comment by apuyou** [comment]
En gros !

On Tue, Oct 30, 2012 at 5:37 PM, Thomas Recouvreux <notifications@github.com

**Comment by apuyou** [comment]
Et une FAQ aussi.

**Comment by trecouvr** [comment]
On la met ou la FAQ ? Une page html static sur payutc/server ?

**Comment by apuyou** [comment]
Dans casper j'aurai dit tout simplement, c'est une faq pour les utilisateurs.

Je vois où tu voudrais en venir à le stocker dans le serveur, mais ça me parait un peu too much perso...
