### ISSUE TITLE
Rendre le champ "montant" de l'interface de virement plus tolérante

### ISSUE THREAD

**Issue by mattgu74** [payutc/casper#3]
Petit message qu'on a reçu : 

"pour les virements, si on met les centimes derriere une virgule ça ne marche pas. Il faut mettre un point. Puis bon comme on est en France (cocorico tout ça..)"

**Comment by apuyou** [comment]
Si jamais ça peut servir (mais je pense qu'ici vaut mieux le gérer côté serveur), j'avais mis ça au Polar :

```
$('.money').keyup(function(e) {
        var value = $(this).val().replace(new RegExp(',', 'g'), '.');
        value = value.replace(new RegExp('[^0-9\.]', 'g'), '');
        $(this).val(value);
});
```

**Comment by apuyou** [comment]
Par ailleurs, le `input type="number"` est pas mal pour les mobiles, mais sur Chrome il capture la molette quand on défile (et les +/- sont inutiles).
