### ISSUE TITLE
Optimisation mobile

### ISSUE THREAD

**Issue by apuyou** [payutc/casper#9]
- [x] Tester l'interface sur mobile et optimiser pour que ce soit au top
- [ ] Détecter quand il s'agit d'un mobile et le dire à Paybox

**Comment by mattgu74** [comment]
Il faut ajouter un parametre optionel à cette méthode : 
https://github.com/payutc/server/blob/master/services/MADMIN.service.php#L329

Et l'envoyer à cette méthode qui gére déjà l'option "mobile"
https://github.com/payutc/server/blob/master/class/Paybox.class.php#L40

ça c'est pour le server, y'a deux lignes à modifier.

**Comment by apuyou** [comment]
Fait dans #22
